// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://deuxhvgusaiujdlzwtua.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldXhodmd1c2FpdWpkbHp3dHVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyOTgxMDYsImV4cCI6MjA1OTg3NDEwNn0.sZ6efK6KEJCot5LGdSuR-4yu-LfacxxEEMPirzX-pyc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);